import type { OrganizationRole } from '../../../types/auth'
import type { ModuleCode } from '../../../types/subscription'
import type { NovaQuickActionDefinition } from '../types/nova.types'

export const NOVA_QUICK_ACTIONS_CATALOG: NovaQuickActionDefinition[] = [
    {
        id: 'onboarding_create_product',
        groupKey: 'gettingStarted',
        labelKey: 'nova.quickActions.createProduct',
        helpKey: 'nova.quickActions.createProductHelp',
        guideKey: 'nova.quickActions.guides.createProduct',
        navigateTo: '/products/new',
        mode: 'hybrid',
        requiredModule: 'INVENTORY',
        minimumRole: 'MANAGER',
        onboarding: true,
    },
    {
        id: 'onboarding_first_sale',
        groupKey: 'gettingStarted',
        labelKey: 'nova.quickActions.newSale',
        helpKey: 'nova.quickActions.newSaleHelp',
        guideKey: 'nova.quickActions.guides.createSale',
        navigateTo: '/sales/new',
        mode: 'hybrid',
        minimumRole: 'CASHIER',
        onboarding: true,
    },
    {
        id: 'onboarding_dashboard',
        groupKey: 'gettingStarted',
        labelKey: 'nova.quickActions.dashboard',
        helpKey: 'nova.quickActions.dashboardHelp',
        executeMessageKey: 'nova.quickActions.execute.dashboardSummary',
        executeActionLabelKey: 'nova.quickActions.executeAction.dashboard',
        navigateTo: '/',
        mode: 'hybrid',
        minimumRole: 'CASHIER',
        onboarding: true,
    },
    {
        id: 'search_product',
        groupKey: 'products',
        labelKey: 'nova.quickActions.searchProduct',
        helpKey: 'nova.quickActions.searchProductHelp',
        guideKey: 'nova.quickActions.guides.searchProduct',
        navigateTo: '/products',
        mode: 'hybrid',
        requiredModule: 'INVENTORY',
        minimumRole: 'MANAGER',
    },
    {
        id: 'create_product',
        groupKey: 'products',
        labelKey: 'nova.quickActions.createProduct',
        helpKey: 'nova.quickActions.createProductHelp',
        guideKey: 'nova.quickActions.guides.createProduct',
        navigateTo: '/products/new',
        mode: 'hybrid',
        requiredModule: 'INVENTORY',
        minimumRole: 'MANAGER',
    },
    {
        id: 'restock',
        groupKey: 'products',
        labelKey: 'nova.quickActions.restock',
        helpKey: 'nova.quickActions.restockHelp',
        guideKey: 'nova.quickActions.guides.restock',
        navigateTo: '/stock/restock',
        mode: 'hybrid',
        requiredModule: 'INVENTORY',
        minimumRole: 'MANAGER',
    },
    {
        id: 'update_product',
        groupKey: 'products',
        labelKey: 'nova.quickActions.updateProduct',
        helpKey: 'nova.quickActions.updateProductHelp',
        guideKey: 'nova.quickActions.guides.updateProduct',
        navigateTo: '/products',
        mode: 'hybrid',
        requiredModule: 'INVENTORY',
        minimumRole: 'MANAGER',
    },
    {
        id: 'deactivate_product',
        groupKey: 'products',
        labelKey: 'nova.quickActions.deactivateProduct',
        helpKey: 'nova.quickActions.deactivateProductHelp',
        guideKey: 'nova.quickActions.guides.deactivateProduct',
        navigateTo: '/products',
        mode: 'hybrid',
        requiredModule: 'INVENTORY',
        minimumRole: 'MANAGER',
    },
    {
        id: 'update_stock',
        groupKey: 'products',
        labelKey: 'nova.quickActions.updateStock',
        helpKey: 'nova.quickActions.updateStockHelp',
        guideKey: 'nova.quickActions.guides.updateStock',
        navigateTo: '/stock/restock',
        mode: 'hybrid',
        requiredModule: 'INVENTORY',
        minimumRole: 'MANAGER',
    },
    {
        id: 'export_products',
        groupKey: 'products',
        labelKey: 'nova.quickActions.exportProducts',
        helpKey: 'nova.quickActions.exportProductsHelp',
        executeMessageKey: 'nova.quickActions.execute.exportProducts',
        executeActionLabelKey: 'nova.quickActions.executeAction.exportProducts',
        navigateTo: '/products',
        mode: 'hybrid',
        requiredModule: 'INVENTORY',
        minimumRole: 'MANAGER',
        showsNovaBadge: true,
    },
    {
        id: 'search_supplier',
        groupKey: 'suppliers',
        labelKey: 'nova.quickActions.searchSupplier',
        helpKey: 'nova.quickActions.searchSupplierHelp',
        guideKey: 'nova.quickActions.guides.searchSupplier',
        navigateTo: '/suppliers',
        mode: 'hybrid',
        requiredModule: 'INVENTORY',
        minimumRole: 'MANAGER',
    },
    {
        id: 'create_supplier',
        groupKey: 'suppliers',
        labelKey: 'nova.quickActions.createSupplier',
        helpKey: 'nova.quickActions.createSupplierHelp',
        guideKey: 'nova.quickActions.guides.createSupplier',
        navigateTo: '/suppliers/new',
        mode: 'hybrid',
        requiredModule: 'INVENTORY',
        minimumRole: 'MANAGER',
    },
    {
        id: 'update_supplier',
        groupKey: 'suppliers',
        labelKey: 'nova.quickActions.updateSupplier',
        helpKey: 'nova.quickActions.updateSupplierHelp',
        guideKey: 'nova.quickActions.guides.updateSupplier',
        navigateTo: '/suppliers',
        mode: 'hybrid',
        requiredModule: 'INVENTORY',
        minimumRole: 'MANAGER',
    },
    {
        id: 'dashboard_summary',
        groupKey: 'dashboard',
        labelKey: 'nova.quickActions.dashboard',
        helpKey: 'nova.quickActions.dashboardHelp',
        executeMessageKey: 'nova.quickActions.execute.dashboardSummary',
        executeActionLabelKey: 'nova.quickActions.executeAction.dashboard',
        navigateTo: '/',
        mode: 'hybrid',
        showsNovaBadge: true,
        minimumRole: 'CASHIER',
    },
    {
        id: 'low_stock',
        groupKey: 'dashboard',
        labelKey: 'nova.quickActions.lowStock',
        helpKey: 'nova.quickActions.lowStockHelp',
        executeMessageKey: 'nova.quickActions.execute.lowStock',
        executeActionLabelKey: 'nova.quickActions.executeAction.lowStock',
        navigateTo: '/products?stock=low',
        mode: 'hybrid',
        requiredModule: 'INVENTORY',
        minimumRole: 'MANAGER',
    },
    {
        id: 'list_sales',
        groupKey: 'sales',
        labelKey: 'nova.quickActions.listSales',
        helpKey: 'nova.quickActions.listSalesHelp',
        executeMessageKey: 'nova.quickActions.execute.listSales',
        executeActionLabelKey: 'nova.quickActions.executeAction.listSales',
        navigateTo: '/sales',
        mode: 'hybrid',
        showsNovaBadge: true,
        minimumRole: 'CASHIER',
    },
    {
        id: 'show_sale',
        groupKey: 'sales',
        labelKey: 'nova.quickActions.showSale',
        helpKey: 'nova.quickActions.showSaleHelp',
        guideKey: 'nova.quickActions.guides.showSale',
        navigateTo: '/sales',
        mode: 'hybrid',
        minimumRole: 'CASHIER',
    },
    {
        id: 'daily_sales_summary',
        groupKey: 'sales',
        labelKey: 'nova.quickActions.dailySalesSummary',
        helpKey: 'nova.quickActions.dailySalesSummaryHelp',
        executeMessageKey: 'nova.quickActions.execute.dailySalesSummary',
        executeActionLabelKey: 'nova.quickActions.executeAction.dailySalesSummary',
        navigateTo: '/sales/daily',
        mode: 'hybrid',
        minimumRole: 'CASHIER',
    },
    {
        id: 'create_sale',
        groupKey: 'sales',
        labelKey: 'nova.quickActions.createSale',
        helpKey: 'nova.quickActions.createSaleHelp',
        guideKey: 'nova.quickActions.guides.createSale',
        navigateTo: '/sales/new',
        mode: 'hybrid',
        minimumRole: 'CASHIER',
    },
    {
        id: 'emit_invoice',
        groupKey: 'sales',
        labelKey: 'nova.quickActions.emitInvoice',
        helpKey: 'nova.quickActions.emitInvoiceHelp',
        guideKey: 'nova.quickActions.guides.emitInvoice',
        navigateTo: '/sales',
        mode: 'hybrid',
        requiredModule: 'FISCAL',
        minimumRole: 'MANAGER',
    },
    {
        id: 'search_customer',
        groupKey: 'customersFiscal',
        labelKey: 'nova.quickActions.searchCustomer',
        helpKey: 'nova.quickActions.searchCustomerHelp',
        guideKey: 'nova.quickActions.guides.searchCustomer',
        navigateTo: '/customers',
        mode: 'hybrid',
        requiredModule: 'CUSTOMERS',
        minimumRole: 'MANAGER',
    },
    {
        id: 'show_customer',
        groupKey: 'customersFiscal',
        labelKey: 'nova.quickActions.showCustomer',
        helpKey: 'nova.quickActions.showCustomerHelp',
        guideKey: 'nova.quickActions.guides.showCustomer',
        navigateTo: '/customers',
        mode: 'hybrid',
        requiredModule: 'CUSTOMERS',
        minimumRole: 'MANAGER',
    },
    {
        id: 'list_fiscal_documents',
        groupKey: 'customersFiscal',
        labelKey: 'nova.quickActions.listFiscalDocuments',
        helpKey: 'nova.quickActions.listFiscalDocumentsHelp',
        executeMessageKey: 'nova.quickActions.execute.listFiscalDocuments',
        executeActionLabelKey: 'nova.quickActions.executeAction.listFiscalDocuments',
        navigateTo: '/fiscal-documents',
        mode: 'hybrid',
        showsNovaBadge: true,
        requiredModule: 'FISCAL',
        minimumRole: 'MANAGER',
    },
    {
        id: 'show_fiscal_document',
        groupKey: 'customersFiscal',
        labelKey: 'nova.quickActions.showFiscalDocument',
        helpKey: 'nova.quickActions.showFiscalDocumentHelp',
        guideKey: 'nova.quickActions.guides.showFiscalDocument',
        navigateTo: '/fiscal-documents',
        mode: 'hybrid',
        requiredModule: 'FISCAL',
        minimumRole: 'MANAGER',
    },
]

export const NOVA_QUICK_ACTION_GROUP_ORDER = [
    'gettingStarted',
    'products',
    'suppliers',
    'dashboard',
    'sales',
    'customersFiscal',
] as const

export type NovaQuickActionGroupKey = (typeof NOVA_QUICK_ACTION_GROUP_ORDER)[number]

export function isNovaQuickActionAvailable(
    action: NovaQuickActionDefinition,
    hasModule: (moduleCode: ModuleCode) => boolean,
    hasMinimumRole: (minimumRole: OrganizationRole) => boolean,
): boolean {
    if (action.requiredModule && !hasModule(action.requiredModule)) {
        return false
    }

    if (action.minimumRole && !hasMinimumRole(action.minimumRole)) {
        return false
    }

    return true
}
